///DrivePriorities()

//Falling Asleep
Drive1FinalPriority = Drive1FinalPriority
- ((1 / 100) * mCreatureController.Stress)
- ((1 / 100) * mCreatureController.Lust)
+ ((1 / 100) * mEmotionSubController.HappyActivation)
+ ((1 / 100) * mEmotionSubController.SadActivation)
- ((2 / 100) * mEmotionSubController.FearActivation)
- ((1 / 100) * mEmotionSubController.SurpriseActivation)
+ ((2 / 100) * mCreatureController.Tiredness)
- ((1 / 100) * mCreatureController.Pain)
- ((1 / 100) * mCreatureController.Dirt)
- ((2 / 100) * mCreatureController.CloseToAnne)
+ (1 * TODMOD)
+ ((1 / 50) * (mCreatureController.Trust - 50))
+ (1 * mCreatureController.Triad) 
+ ((1 * mWorldController.LightLevelInMB))
+ ((1 / 5000) * NoInteractionTimer)
+ (1 * EatenToday)
- ((1.5 / 3200) * Drive1ChanceCooldown)


//Player Leave
Drive2FinalPriority = Drive2FinalPriority
+ ((1 / 100) * mCreatureController.Stress)
- ((2 / 100) * mEmotionSubController.FearActivation)
+ ((2 / 100) * mEmotionSubController.AngerActivation)
- ((1 / 100) * mEmotionSubController.HappyActivation)
+ ((1 / 100) * mCreatureController.Tiredness)
- ((1 / 100) * (100 - mCreatureController.Alive))
- ((1 / 100) * mEmotionSubController.HappyActivation)
+ ((1 / 100) * mCreatureController.Pain)
- ((1 / 100) * mEmotionSubController.ShameActivation)
- ((1 / 50) * (mCreatureController.Trust - 50))
- (1 * mCreatureController.Triad) 
- ((2 / 100) * mCreatureController.CloseToAnne)
- ((1 / 100) * (100 - mBehavioursDeliberative.PercentForward))
- (1 * mInterfaceController.PressBegun)
+ ((1 / 5) * mInterfaceController.Taps)
+ ((1 / 100) * mCreatureController.Resistance)
- ((1.5 / 3200) * Drive2ChanceCooldown)


//Player Come
Drive3FinalPriority = Drive3FinalPriority
+ (((1 / 100) * mCreatureController.Stress) * mCreatureController.Triad)
+ (((1 / 100) * mCreatureController.Pain) * mCreatureController.Triad)
+ ((1 / 100) * mCreatureController.Tiredness)
+ ((1 / 100) * (100 - mCreatureController.Alive))
- ((1 / 100) * mCreatureController.CloseToAnne)
+ ((1 / 100) * mEmotionSubController.SadActivation)
- ((1 / 100) * mEmotionSubController.ShameActivation)
+ ((1 / 50) * (mCreatureController.Trust - 50))
+ (1 * mCreatureController.Triad)
+ ((1 / 100) * mCreatureController.Lust)
+ ((1 / 100) * mEmotionSubController.HappyActivation)
- ((1 / 100) * mEmotionSubController.AngerActivation)
+ (((1 / 100) * mEmotionSubController.FearActivation) * mCreatureController.Triad)
+ ((1 / 5000) * NoInteractionTimer)
+ ((1 * mWorldController.LightLevelInMB))
- ((1 / 100) * mCreatureController.Resistance)
- ((1.5 / 3200) * Drive3ChanceCooldown)

//Flee
Drive4FinalPriority = Drive4FinalPriority
+ ((1 / 100) * mCreatureController.Stress)
- ((1 / 100) * mCreatureController.Tiredness)
+ ((1 / 100) * mCreatureController.Pain)
- ((2 / 100) * (100 - mCreatureController.Alive))
- ((2 / 100) * mCreatureController.CloseToAnne)
- ((1 / 100) * mEmotionSubController.HappyActivation)
+ ((1 / 100) * mEmotionSubController.SadActivation)
+ ((1 / 100) * mEmotionSubController.ShameActivation)
+ ((2 / 100) * mEmotionSubController.FearActivation)
+ ((1 / 100) * mEmotionSubController.AngerActivation)
- ((1 / 50) * (mCreatureController.Trust - 50))
- (1 * TODMOD)
+ ((1 / 100) * mCreatureController.Dirt)
- (1 * mCreatureController.Triad)
- ((1.5 / 3200) * Drive4ChanceCooldown)


//Retreat
Drive5FinalPriority = Drive5FinalPriority
+ ((1 / 100) * mCreatureController.Stress)
+ ((1 / 100) * mCreatureController.Tiredness)
- (((1 / 100) * mCreatureController.Pain) * mCreatureController.Triad)
- ((2 / 100) * (100 - mCreatureController.Alive))
- ((2 / 100) * mCreatureController.CloseToAnne)
- (((1 / 100) * mEmotionSubController.SadActivation) * mCreatureController.Triad)
+ ((1 / 100) * mEmotionSubController.ShameActivation)
- ((1 / 50) * (mCreatureController.Trust - 50))
- (1 * mCreatureController.Triad)
+ ((1 / 100) * mBehavioursDeliberative.PercentForward)
- ((1 / 100) * mCreatureController.Lust)
- ((1 / 100) * mEmotionSubController.HappyActivation)
+ ((1 / 100) * mEmotionSubController.AngerActivation)
+ ((2 / 100) * mEmotionSubController.FearActivation)
- ((1 * mWorldController.LightLevelInMB))
- (1 * TODMOD)
+ ((1 / 100) * mCreatureController.Resistance)
- ((1.5 / 3200) * Drive5ChanceCooldown)


//ToDefaultPos
Drive6FinalPriority = Drive6FinalPriority
+ ((1 / 100) * mCreatureController.Stress)
+ ((1 / 100) * mCreatureController.Tiredness)
+ ((1 / 100) * mCreatureController.Pain)
- ((1 / 100) * (100 - mCreatureController.Alive))
+ ((1 / 100) * mEmotionSubController.SurpriseActivation)
+ ((1 / 100) * mEmotionSubController.ShameActivation)
+ ((1.5 / 9000) * NoInteractionTimer)
+ ((1 / 100) * mCreatureController.Resistance)
+ ((1 / 100) * mCreatureController.Dirt)
- ((1 / 50) * (mCreatureController.Trust - 50))
- (1 * mCreatureController.Triad)
- ((1 / 100) * mCreatureController.Lust)
- ((1 / 100) * mEmotionSubController.HappyActivation)
+ ((1 / 100) * mEmotionSubController.AngerActivation)
- ((2 / 100) * mEmotionSubController.FearActivation)
+ ((1 / 100) * mCreatureController.Resistance)
- ((1.5 / 3200) * Drive6ChanceCooldown)
- ((2 / 100) * mCreatureController.CloseToAnne)


//Come Forward
Drive7FinalPriority = Drive7FinalPriority
- ((1 / 100) * mCreatureController.Stress)
+ ((2 / 100) * mCreatureController.CloseToAnne)
+ ((1 / 100) * mCreatureController.Lust)
+ ((1 / 100) * (100 - mCreatureController.Alive))
+ (((1 / 100) * mCreatureController.Pain) * mCreatureController.Triad)
+ (((1 / 100) * mEmotionSubController.SadActivation) * mCreatureController.Triad)
- ((1 / 100) * mEmotionSubController.ShameActivation)
+ ((1 / 50) * (mCreatureController.Trust - 50))
+ (1 * mCreatureController.Triad)
- ((1 / 100) * mCreatureController.Resistance)
+ (1 * TODMOD)
+ ((1 * mWorldController.LightLevelInMB))
+ (((2 / 100) * mEmotionSubController.FearActivation) * mCreatureController.Triad)
- ((1 / 100) * mEmotionSubController.AngerActivation)
+ ((1 / 100) * mEmotionSubController.HappyActivation)
- ((mEmotionSubController.HappyWeatherMod) / 10)
- ((1.5 / 3200) * Drive7ChanceCooldown)


//Go To Eat
Drive8FinalPriority = Drive8FinalPriority
+ ((1 / 100) * mCreatureController.Stress)
- ((1 / 100) * mCreatureController.Tiredness)
- ((2 / 100) * mCreatureController.CloseToAnne)
- ((1 / 100) * mCreatureController.Pain)
+ ((1 / 100) * (100 - mCreatureController.Alive))
+ ((1 / 100) * mEmotionSubController.SadActivation)
+ ((1 / 100) * mEmotionSubController.ShameActivation)
- (1 * mCreatureController.Triad)
- ((1 / 100) * mCreatureController.Lust)
+ ((1 / 100) * mEmotionSubController.HappyActivation)
+ ((1 / 100) * mEmotionSubController.AngerActivation)
- ((2 / 100) * mEmotionSubController.FearActivation)
+ ((1 / 100) * mCreatureController.Resistance)
- ((1.5 / 3200) * Drive8ChanceCooldown)

//Doze
Drive10FinalPriority = Drive10FinalPriority
+ ((1 / 100) * mCreatureController.Tiredness)
- ((1 / 100) * mCreatureController.Stress)
- ((2 / 100) * mCreatureController.CloseToAnne)
- ((1 / 100) * mCreatureController.Lust)
+ ((1 / 100) * (100 - mCreatureController.Alive))
+ ((1 / 100) * mEmotionSubController.SadActivation)
- ((1 / 100) * mEmotionSubController.SurpriseActivation)
+ ((1 / 100) * mEmotionSubController.HappyActivation)
- ((1 / 100) * mEmotionSubController.AngerActivation)
- ((2 / 100) * mEmotionSubController.FearActivation)
+ ((1 / 5000) * NoInteractionTimer)
+ ((1 * mWorldController.LightLevelInMB))
+ (1 * EatenToday)
+ ((1 / 50) * (mCreatureController.Trust - 50))
+ (1 * mCreatureController.Triad)
- ((1.5 / 3200) * Drive10ChanceCooldown)

//Stroke Nose
Drive12FinalPriority = Drive12FinalPriority
+ ((1 / 100) * mCreatureController.Stress)
- ((1 / 60) * mCreatureController.Pain)
+ ((1 / 100) * mCreatureController.Tiredness)
+ ((1 / 100) * (100 - mCreatureController.Alive))
+ (((1 / 100) * mEmotionSubController.SadActivation) * mCreatureController.Triad)
- ((1 / 100) * mEmotionSubController.ShameActivation)
+ ((1 / 50) * (mCreatureController.Trust - 50))
+ (1 * mCreatureController.Triad)
- ((1 / 100) * mCreatureController.CloseToAnne)
+ ((1 / 100) * mCreatureController.Lust)
+ ((1 / 100) * mEmotionSubController.HappyActivation)
- ((1 / 100) * mCreatureController.Resistance)
- ((1 / 100) * mEmotionSubController.AngerActivation)
- ((1 / 100) * mEmotionSubController.FearActivation)
- ((1.5 / 3200) * Drive12ChanceCooldown)

//Inspect Mansion
Drive13FinalPriority = Drive13FinalPriority
- ((1 / 100) * mCreatureController.Stress)
- ((1 / 100) * mCreatureController.Tiredness)
+ ((1 / 60) * mCreatureController.Pain)
- ((1 / 100) * mEmotionSubController.SadActivation)
+ ((1 / 100) * mEmotionSubController.SurpriseActivation)
- ((1 / 100) * mEmotionSubController.ShameActivation)
+ ((1 / 50) * (mCreatureController.Trust - 50))
+ (1 * mCreatureController.Triad)
+ ((1 / 100) * mBehavioursDeliberative.PercentForward)
+ ((1 / 100) * mCreatureController.Lust)
+ ((1 / 100) * mEmotionSubController.HappyActivation)
- ((1 / 100) * mEmotionSubController.AngerActivation)
- ((1 / 100) * mEmotionSubController.FearActivation)
+ ((1 * mWorldController.LightLevelInMB))
- ((1 / 100) * mCreatureController.Resistance)
- ((1.5 / 3200) * Drive13ChanceCooldown)
+ ((5 * IsInRitual()))


//Clean Skin
Drive15FinalPriority = Drive15FinalPriority
+ ((1 / 100) * mCreatureController.Stress)
- ((1 / 100) * mCreatureController.Tiredness)
- ((1 / 100) * mCreatureController.Pain)
- ((1 / 100) * (100 - mCreatureController.Alive))
+ ((1 / 100) * mEmotionSubController.SadActivation)
+ ((1 / 100) * mEmotionSubController.ShameActivation)
+ ((1 / 50) * (mCreatureController.Trust - 50))
- ((2 / 100) * mCreatureController.CloseToAnne)
+ ((1 / 5000) * NoInteractionTimer)
- ((1 / 100) * mEmotionSubController.HappyActivation)
+ ((1 / 100) * mEmotionSubController.AngerActivation)
- ((2 / 100) * mEmotionSubController.FearActivation)
- ((1 / 100) * mCreatureController.Resistance)
+ ((1.5 / 100) * mCreatureController.Dirt)
- ((1.5 / 3200) * Drive15ChanceCooldown)

//Player Get Off
Drive16FinalPriority = Drive16FinalPriority
+ ((1 / 100) * mCreatureController.Stress)
+ ((1 / 100) * mCreatureController.Pain)
- ((2 / 100) * mCreatureController.CloseToAnne)
- ((1 / 100) * (100 - mCreatureController.Alive))
+ ((1 / 100) * mEmotionSubController.SadActivation)
- ((2 / 100) * mEmotionSubController.FearActivation)
+ ((1 / 100) * mEmotionSubController.ShameActivation)
- ((1 / 50) * (mCreatureController.Trust - 50))
- (1 * mCreatureController.Triad)
+ ((1 / 100) * mCreatureController.Resistance)
+ ((1 / 100) * mEmotionSubController.AngerActivation)
- ((1 / 100) * mEmotionSubController.HappyActivation)
- ((1 / 100) * mCreatureController.Lust)
- ((1.5 / 3200) * Drive16ChanceCooldown)

//General Vocalise
Drive17FinalPriority = Drive17FinalPriority
- ((1 / 100) * (100 - mCreatureController.Alive))
+ ((1 / 100) * mCreatureController.Stress)
- ((1 / 100) * mCreatureController.Tiredness)
+ ((1 / 100) * mCreatureController.Pain)
+ ((1 / 100) * mEmotionSubController.SadActivation)
- ((1 / 100) * mEmotionSubController.ShameActivation)
- ((1 / 100) * mEmotionSubController.SurpriseActivation)
+ ((1 / 5000) * NoInteractionTimer)
+ ((1 * mWorldController.LightLevelInMB))
+ ((1 / 100) * mCreatureController.Resistance)
- ((2 / 100) * mEmotionSubController.FearActivation)
+ ((1 / 100) * mEmotionSubController.AngerActivation)
+ ((1 / 100) * mEmotionSubController.HappyActivation)
- ((1 / 100) * mCreatureController.Lust)
- ((2 / 100) * mCreatureController.CloseToAnne)
+ ((1 / 50) * (mCreatureController.Trust - 50))
+ (1 * mCreatureController.Triad)
- ((1.5 / 3200) * Drive17ChanceCooldown)


//Touch Caul
Drive18FinalPriority = Drive18FinalPriority
- ((1 / 100) * mCreatureController.Stress)
- ((1 / 100) * mCreatureController.Tiredness)
- ((1 / 100) * mCreatureController.Pain)
+ ((1 / 100) * (100 - mCreatureController.Alive))
+ ((1 / 100) * mEmotionSubController.SadActivation)
- ((1 / 100) * mEmotionSubController.SurpriseActivation)
- ((1 / 100) * mEmotionSubController.ShameActivation)
+ ((1 / 300) * EjacTrack)
+ ((1 / 50) * (mCreatureController.Trust - 50))
+ (1 * mCreatureController.Triad)
+ ((2 / 100) * mCreatureController.CloseToAnne)
+ ((1.5 / 100) * mCreatureController.Lust)
+ ((1 / 100) * mEmotionSubController.HappyActivation)
- ((1 / 100) * mEmotionSubController.AngerActivation)
- ((2 / 100) * mEmotionSubController.FearActivation)
- ((1 / 5000) * NoInteractionTimer)
+ (1 * TODMOD)
- ((1 / 100) * mCreatureController.Resistance)
- ((1 / 100) * mCreatureController.Dirt)
+ (1 * PlayerViewOverObject(mCaulParent))
- ((1.5 / 3200) * Drive18ChanceCooldown)


//Player Touch
Drive21FinalPriority = Drive21FinalPriority
+ (TimeSinceLastTouch / 2000)
- ((1 / 100) * mCreatureController.Stress)
- ((1 / 100) * mCreatureController.Pain)
+ ((1 / 100) * (100 - mCreatureController.Alive))
- ((1 / 100) * mEmotionSubController.SadActivation)
- ((1 / 100) * mEmotionSubController.ShameActivation)
+ ((1 / 50) * (mCreatureController.Trust - 50))
+ (1 * mCreatureController.Triad)
- ((2 / 100) * mCreatureController.CloseToAnne)
+ ((1 / 100) * mCreatureController.Lust)
+ ((1 / 100) * mEmotionSubController.HappyActivation)
- ((1 / 100) * mEmotionSubController.AngerActivation)
- (((2 / 100) * mEmotionSubController.FearActivation) * mCreatureController.Triad)
+ ((1 / 5000) * NoInteractionTimer)
- ((1 / 100) * mCreatureController.Resistance)
- ((1 / 100) * mCreatureController.Tiredness)
+ ((1 / 100) * mCreatureController.Dirt)
+ (instance_number(oWen) / 100)
+ (instance_number(oWound) / 100)
- ((1.5 / 3200) * Drive21ChanceCooldown)


//Zoom Out
Drive22FinalPriority = Drive22FinalPriority
+ (mInterfaceController.ZoomedInTimer / 2000)
+ ((1 / 100) * mCreatureController.Pain)
+ ((1 / 100) * mCreatureController.Stress)
+ (1 * mCreatureController.Triad)
- ((2 / 100) * mCreatureController.CloseToAnne)
- ((1 / 100) * mCreatureController.Trust)
+ ((1 / 100) * mCreatureController.Resistance)
+ ((1 / 100) * mEmotionSubController.AngerActivation)
+ ((1 / 100) * mEmotionSubController.SadActivation)
- ((2 / 100) * mEmotionSubController.FearActivation)
+ ((1 / 5000) * NoInteractionTimer)
- ((1.5 / 3200) * Drive22ChanceCooldown)



