instance_create(x,y,mAnatomy)
instance_create(x,y,oLeftEye)
instance_create(x,y,oLeftBrow)
instance_create(x,y,oRightEye)
instance_create(x,y,oRightBrow)
instance_create(x,y,oNose1)
instance_create(x,y,oNose2)
instance_create(x,y,oNose3)
instance_create(x,y,oNose4)
instance_create(x,y,oNose5)
instance_create(x,y,oNose6)
instance_create(x,y,oLeftNostril)
instance_create(x,y,oRightNostril)
instance_create(x,y,oMouth)
instance_create(x,y,mIrritationDetector)

